console.log(1 + 2); // 3
console.log(1 + +2); // 3
console.log(1 + +(+2)); // 3
console.log(1 + "2"); // 12
console.log(1 + +"2"); //3
console.log("1" + 2); // 12
console.log("1" + +2); // 12
console.log(1 + true); // 2
console.log(1 + +true); // 2
console.log("1" + true); // 1true
console.log("1" + +true); // 11
console.log(1 + null); // 1
console.log(1 + +null); // 1
console.log("1" + null); // 1null
console.log("1" + +null); // 10
console.log(1 + undefined); // NaN
console.log(1 + +undefined); // NaN
console.log("1" + undefined); // 1undefined
console.log("1" + +undefined); // 1NaN
console.log("1" + +(+undefined)); // 1NaN
